apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: didis/api-spring:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL         
          value: "jdbc:postgresql://192.168.99.100:30605/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "testpassword"

