apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pgsql
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: didis/api-spring:v3
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef: 
              name: app-config
